
# You can change the default http port
server:
  port: 8080
  servlet:
    path: /njdp

# default db config

## Mybatis 配置typeAliasesPackage: com.njty.tydp.mapper

spring:
  datasource:
    url: jdbc:mysql://47.110.88.109:3306/cz_car?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: gesoft123!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #url: jdbc:oracle:thin:@58.213.107.82:1521:orcl
    #username: buspos
    #password: njtynjty
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    #type: com.alibaba.druid.pool.DruidDataSource


#配置日志
logging:
  #配置日志文件路径
  level:
    com.njty.njdp: debug #不同目录下的日志可配置不同级别
    com.njty.njdp.mapper: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    #org.hibernate: info
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log

